### ISSUE TITLE
Change to Loki

### ISSUE THREAD

**Issue by sinanboecker** [brejoc/isisisreleasedyet.com#4]
https://launchpad.net/elementaryos/+milestone/loki-beta1

**Comment by brejoc** [comment]
I don't think that would make much sense, especially since there is a much [better overview on the official elementary website](https://elementary.io/de/get-involved).

But let me ask you a question, @gorrila. Would a version of IFRY for Loki really be so appealing?

**Comment by brejoc** [comment]
This is very old. I don't think we need this anymore.
